name: sliding_drawer
version: 1.0.0
description: A Flutter widget that provides a drawer with the sliding effect.
homepage: https://github.com/Ilya-Korolev/sliding_drawer
repository: https://github.com/Ilya-Korolev/sliding_drawer
documentation: https://github.com/Ilya-Korolev/sliding_drawer
issue_tracker: https://github.com/Ilya-Korolev/sliding_drawer/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.1.0
